import { sql } from "drizzle-orm";
import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * better-auth tables (`user`, `session`, `account`, `verification`),
 * generated by `pnpm dlx @better-auth/cli@latest generate --output
 * src/db/auth-schema.ts`. Re-exported here so `drizzle-kit` picks them up
 * for migrations and `src/lib/auth.ts`'s `drizzleAdapter` sees them via this
 * same barrel's `schema` import. Do not hand-edit `auth-schema.ts` — re-run
 * the CLI (e.g. after enabling a plugin) to regenerate it.
 */
export * from "./auth-schema";

/**
 * Consorcios - top-level entity representing a "consorcio" managed in the
 * app. Bootstrap table for the domain schema.
 *
 * Add further domain tables below this one, in their own exported
 * `pgTable(...)` blocks, following this same style (uuid surrogate PK,
 * snake_case columns, `createdAt`/`updatedAt` timestamps).
 */
export const consorcios = pgTable("consorcios", {
  id: uuid("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  nombre: text("nombre").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export type Consorcio = typeof consorcios.$inferSelect;
export type NuevoConsorcio = typeof consorcios.$inferInsert;

// --- Domain tables ---
// Add new domain tables (e.g. unidades, propietarios, gastos) below, each
// as its own exported `pgTable(...)` with its inferred `$inferSelect` /
// `$inferInsert` types, following the `consorcios` table above as the
// reference pattern.
