import { sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

import type { Recipient } from "@/lib/schemas/email";

import { user } from "./auth-schema";

/**
 * better-auth tables (`user`, `session`, `account`, `verification`),
 * generated by `pnpm dlx @better-auth/cli@latest generate --output
 * src/db/auth-schema.ts`. Re-exported here so `drizzle-kit` picks them up
 * for migrations and `src/lib/auth.ts`'s `drizzleAdapter` sees them via this
 * same barrel's `schema` import. Do not hand-edit `auth-schema.ts` — re-run
 * the CLI (e.g. after enabling a plugin) to regenerate it.
 */
export * from "./auth-schema";

/**
 * Consortiums — top-level entity owned by an authenticated user (`ownerId`).
 * Soft-deleted rows keep `isDeleted = true` and are excluded from list/detail.
 */
export const consortiums = pgTable(
  "consortiums",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    name: text("name").notNull(),
    location: text("location").notNull(),
    paymentAlias: text("payment_alias"),
    billingEmail: text("billing_email"),
    driveLink: text("drive_link"),
    amount: integer("amount").notNull().default(0),
    ownerId: text("owner_id")
      .notNull()
      .references(() => user.id),
    isDeleted: boolean("is_deleted").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("consortiums_owner_id_active_idx")
      .on(table.ownerId)
      .where(sql`${table.isDeleted} = false`),
  ],
);

export type ConsortiumRow = typeof consortiums.$inferSelect;
export type NewConsortium = typeof consortiums.$inferInsert;

// --- Domain tables ---
// Add new domain tables (e.g. units, owners, expenses) below, each
// as its own exported `pgTable(...)` with its inferred `$inferSelect` /
// `$inferInsert` types, following the `consortiums` table above as the
// reference pattern.

/**
 * Email log - one row per email send attempt (single email or batch),
 * recording who sent it, to whom, and the outcome reported by Resend.
 */
export const emailLog = pgTable(
  "email_log",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    subject: text("subject").notNull(),
    body: text("body").notNull(),
    /** Recipients this email was sent to. */
    recipients: jsonb("recipients").notNull().$type<Recipient[]>(),
    recipientCount: integer("recipient_count").notNull(),
    /** Outcome reported by Resend, e.g. "sent", "partial", or "failed". */
    status: text("status").notNull(),
    /** Resend message ids returned for each successfully sent email. */
    resendIds: jsonb("resend_ids").$type<string[]>(),
    error: text("error"),
    sentByUserId: text("sent_by_user_id").references(() => user.id),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("email_log_created_at_idx").on(table.createdAt)],
);

export type EmailLog = typeof emailLog.$inferSelect;
export type NewEmailLog = typeof emailLog.$inferInsert;
